[package]
authors = ["Gavin Gray <gagray@ethz.ch>"]
name = "aquascope_serve"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
aquascope_front = {version = "0.1", path = "../aquascope_front"}
async-trait = "0.1.52"
axum = { version = "0.5", features = ["headers"] }
axum-macros = "0.2"
env_logger = "0.9.0"
futures = "0.3.21"
log = "0.4.0"
serde = { version = "1.0", features = ["rc", "derive"] }
serde_json = "1.0"
snafu = "0.7.0"
tokio = { version = "1.9", features = ["macros", "time", "process", "rt-multi-thread"] }
tower-http = { version = "0.3", features = ["cors", "fs", "set-header", "trace"] }
bollard = "0.13"
ts-rs = "6.1"
tar = "0.4"
