[package]
name = "aquascope"
version = "0.1.0"
edition = "2021"
authors = ["Gavin Gray <gavinleroy6@gmail.com>"]
repository = "https://github.com/gavinleroy/aquascope"
license = "MIT"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
anyhow = "1.0.0"
log = "0.4"
itertools = "0.10.5"
flowistry = { path = "../../../flowistry/crates/flowistry" }
# flowistry = "0.5.34"
datafrog = "2.0.0"
serde = "1.0"
ts-rs = "6.1"

# testing
lazy_static = "1.4"

[dev-dependencies]
env_logger = "0.9.3"
test-log = "0.2.11"
