[package]
name = "aquascope"
version = "0.1.0"
edition = "2021"
authors = ["Gavin Gray <gavinleroy6@gmail.com>"]
repository = "https://github.com/gavinleroy/aquascope"
license = "MIT"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
log = "0.4"
flowistry = "0.5.31"
datafrog = "2.0.0"
serde = "1.0"
ts-rs = "6.1"
