name: aquascope

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: davidB/rust-cargo-make@v1
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-insta
          version: latest
          use-tool-cache: true
      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook
          version: latest
          use-tool-cache: true
      - run: cargo make init-bindings
      - run: npm install -g graco && cd frontend && graco prepare
      - run: cargo miri setup
      - run: cargo install --path crates/aquascope_front --debug
      - run: cargo install --path crates/mdbook-aquascope --debug
      - run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(rustc --print target-libdir)
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.25'
      - run: cd crates/mdbook-aquascope/test-book && mdbook build
      - name: Backend tests
        uses: actions-rs/cargo@v1
        with:
          command: insta
          args: test --features=no-docker
      - name: Frontend tests
        run: |
          cd crates/aquascope_serve && cargo run --features=no-docker &
          sleep 120
          cd frontend
          graco build -w &
          sleep 15
          graco test
