name: aquascope

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/workflows/setup
      - name: Backend tests
        uses: actions-rs/cargo@v1
        with:
          command: insta
          args: test --features=no-docker
      - name: Frontend tests
        run: |
          cd crates/aquascope_serve && cargo run --features=no-docker &
          sleep 120
          cd frontend
          graco build -w &
          sleep 15
          graco test
