name: release

on:
  push:
    tags:
      - "v*"

jobs:
  publish-standalone-and-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: npm install -g graco && cd frontend && graco prepare
      - run: cargo doc --lib && mv ./target/doc ./frontend/packages/aquascope-standalone/dist/doc
      - uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: ./frontend/packages/aquascope-standalone/dist
          clean: true
          clean-exclude: dev
